<style>
.header_redsys{
    padding: 25px;
    margin-bottom: 25px;
    border: #ADC0C0 1px solid;
    background-color: #E7EFEF;
}
</style>
<div class="header_redsys">
    <?php echo $this->__('Module developed by <a href="http://devopensource.com/">Devopensource.com</a> if you need support contact with <a href="mailto:info@devopensource.com" >info@devopensource.com</a> or help us keep the module <a href="https://github.com/DevopensourceTeam/Devopensource_Redsys" >in github</a>. You can view the <a href="https://github.com/DevopensourceTeam/Devopensource_Redsys/wiki">documentation here</a>'); ?>
</div>
