<style>
.header_redsys{
    padding: 25px;
    margin-bottom: 25px;
    border: #D6D6D6 1px solid;
    background-color: #E2DEDE;
}
</style>
<div class="header_redsys">
    <?php echo $this->__('Module developed by <a href="http://devopensource.com/">Devopensource.com</a> if you need support contact with <a href="mailto:info@devopensource.com" >info@devopensource.com</a> or help us keep the module <a href="https://github.com/DevopensourceTeam/Devopensource_Redsys" >in github</a>.'); ?>
</div>
